"""add file_path to buku

Revision ID: 616e6aff1d1d
Revises: 9d6a2c1ae73d
Create Date: 2025-12-02 16:32:35.439447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e6aff1d1d'
down_revision = '9d6a2c1ae73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buku', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
