"""initial

Revision ID: 9d6a2c1ae73d
Revises: 
Create Date: 2025-12-02 15:32:27.903722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6a2c1ae73d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('kelas', sa.Integer(), nullable=False),
    sa.Column('jumlah_halaman', sa.Integer(), nullable=False),
    sa.Column('penerbit', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misi_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('jumlah_soal', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('soal_misi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('teks_soal', sa.Text(), nullable=False),
    sa.Column('opsi_a', sa.Text(), nullable=True),
    sa.Column('opsi_b', sa.Text(), nullable=True),
    sa.Column('opsi_c', sa.Text(), nullable=True),
    sa.Column('opsi_d', sa.Text(), nullable=True),
    sa.Column('kunci_pg', sa.String(length=1), nullable=True),
    sa.Column('kunci_isian', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'nomor', name='uq_soal_misi_level_nomor')
    )
    with op.batch_alter_table('soal_misi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soal_misi_level'), ['level'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=150), nullable=True),
    sa.Column('kelas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('soal_misi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soal_misi_level'))

    op.drop_table('soal_misi')
    op.drop_table('misi_level')
    op.drop_table('buku')
    # ### end Alembic commands ###
